# Generated by Django 4.1.4 on 2023-03-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                ("image", models.ImageField(upload_to="pics")),
                ("description", models.TextField()),
            ],
        ),
    ]
