# Generated by Django 4.1.4 on 2023-03-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app0", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
