# Generated by Django 4.1.4 on 2023-03-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app0", "0002_alter_place_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Place",
            new_name="Travello",
        ),
    ]
