# Generated by Django 4.1.4 on 2023-03-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app0", "0003_rename_place_travello"),
    ]

    operations = [
        migrations.RenameField(
            model_name="travello",
            old_name="name",
            new_name="nam",
        ),
    ]
