# Generated by Django 4.1.4 on 2023-03-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app0", "0004_rename_name_travello_nam"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Travello",
            new_name="Place",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="description",
            new_name="desc",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="image",
            new_name="img",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="nam",
            new_name="name",
        ),
    ]
