# Generated by Django 4.1.4 on 2023-03-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app0", "0006_rename_place_travel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="pics")),
                ("name1", models.CharField(max_length=250)),
                ("pos", models.CharField(max_length=250)),
                ("description", models.TextField()),
            ],
        ),
    ]
